### PR TITLE
Fix early close time.

### LINKED ISSUE #135: XLIS: Wrong or ambiguous early close time for XLIS.
*This applies to version 2020.1 and possibly earlier versions.*

The returned early close time of 14:05 for XLIS, e.g. on 2020-12-24, is incorrect or at least ambiguous. It is incorrect if the time is meant to be in the exchange's time zone -- which is WET -- since the time is correct only in CET; cf. https://www.euronext.com/en/trade/trading-hours-holidays which lists the early close time as 14:05 CET for several Euronext exchanges that are located in both CET and WET (Lisbon) time zones. It is ambiguous if the user is expected to interpret the time in CET since there's no link to that time zone from the XLIS calendar.

### PR DESCRIPTION
**Pull request by jenskeiner**
Convert the early close time 14:05 CET into local time in WET, i.e. 13:05.

To fix #135.

### CODE REVIEW

**Comment by jenskeiner** [comment]
I can't download the logs of the failing tests at this moment. But I reckon my simple code change didn't consider that the early closing times for past years <= 2019 were correct, but we're affected by my change as well. I will try to fix, but any help from more regular project contributers would be appreciated.

**Comment by gerrymanoim** [comment]
Hey @jenskeiner - I agree that times should be in the local time of the market, thanks for catching this and the PR!

Can you elaborate on why the logs are inaccessible? Is there a permissions issue on our side or something on your end?

If it helps - here are is the failing test output:

```
2020-07-06T11:50:13.8235893Z ======================================================================
2020-07-06T11:50:13.8236316Z ERROR: test_minute_to_session_label (tests.test_xlis_calendar.XLISCalendarTestCase)
2020-07-06T11:50:13.8237110Z ----------------------------------------------------------------------
2020-07-06T11:50:13.8237254Z Traceback (most recent call last):
2020-07-06T11:50:13.8238824Z   File "/home/runner/work/trading_calendars/trading_calendars/tests/test_trading_calendar.py", line 433, in test_minute_to_session_label
2020-07-06T11:50:13.8239069Z     direction="none"),
2020-07-06T11:50:13.8239310Z   File "/home/runner/work/trading_calendars/trading_calendars/trading_calendars/trading_calendar.py", line 831, in minute_to_session_label
2020-07-06T11:50:13.8239496Z     Given a minute, get the label of its containing session.
2020-07-06T11:50:13.8239718Z   File "/home/runner/work/trading_calendars/trading_calendars/trading_calendars/trading_calendar.py", line 872, in minute_to_session_label
2020-07-06T11:50:13.8239941Z     raise ValueError("The given dt is not an exchange minute!")
2020-07-06T11:50:13.8240086Z ValueError: The given dt is not an exchange minute!
2020-07-06T11:50:13.8240187Z 
2020-07-06T11:50:13.8240322Z ======================================================================
2020-07-06T11:50:13.8240458Z FAIL: test_half_days (tests.test_xlis_calendar.XLISCalendarTestCase)
2020-07-06T11:50:13.8240861Z ----------------------------------------------------------------------
2020-07-06T11:50:13.8241001Z Traceback (most recent call last):
2020-07-06T11:50:13.8241211Z   File "/home/runner/work/trading_calendars/trading_calendars/tests/test_trading_calendar.py", line 929, in test_half_days
2020-07-06T11:50:13.8241381Z     half_day + self.TIMEDELTA_TO_EARLY_CLOSE,
2020-07-06T11:50:13.8241788Z AssertionError: Timestamp('2010-12-24 13:05:00+0000', tz='UTC') != Timestamp('2010-12-24 14:05:00+0000', tz='Europe/Lisbon')
2020-07-06T11:50:13.8242354Z     "Timestamp('2010-12-24 13:05:00+0000', tz='UTC') != Timestamp('2010-12-24 14:05:00+0000', tz='Europe/Lisbon')" = '%s != %s' % (safe_repr(Timestamp('2010-12-24 13:05:00+0000', tz='UTC')), safe_repr(Timestamp('2010-12-24 14:05:00+0000', tz='Europe/Lisbon')))
2020-07-06T11:50:13.8243445Z     "Timestamp('2010-12-24 13:05:00+0000', tz='UTC') != Timestamp('2010-12-24 14:05:00+0000', tz='Europe/Lisbon')" = self._formatMessage("Timestamp('2010-12-24 13:05:00+0000', tz='UTC') != Timestamp('2010-12-24 14:05:00+0000', tz='Europe/Lisbon')", "Timestamp('2010-12-24 13:05:00+0000', tz='UTC') != Timestamp('2010-12-24 14:05:00+0000', tz='Europe/Lisbon')")
2020-07-06T11:50:13.8243919Z >>  raise self.failureException("Timestamp('2010-12-24 13:05:00+0000', tz='UTC') != Timestamp('2010-12-24 14:05:00+0000', tz='Europe/Lisbon')")
2020-07-06T11:50:13.8244075Z     
2020-07-06T11:50:13.8244156Z 
2020-07-06T11:50:13.8244285Z ======================================================================
2020-07-06T11:50:13.8244434Z FAIL: test_is_open_on_minute (tests.test_xlis_calendar.XLISCalendarTestCase)
2020-07-06T11:50:13.8244744Z ----------------------------------------------------------------------
2020-07-06T11:50:13.8244881Z Traceback (most recent call last):
2020-07-06T11:50:13.8245109Z   File "/home/runner/work/trading_calendars/trading_calendars/tests/test_trading_calendar.py", line 274, in test_is_open_on_minute
2020-07-06T11:50:13.8245285Z     self.assertTrue(self.calendar.is_open_on_minute(close_minute_utc))
2020-07-06T11:50:13.8245423Z AssertionError: False is not true
2020-07-06T11:50:13.8245777Z     'False is not true' = self._formatMessage('False is not true', "%s is not true" % safe_repr(False))
2020-07-06T11:50:13.8246080Z >>  raise self.failureException('False is not true')
2020-07-06T11:50:13.8246213Z     
2020-07-06T11:50:13.8246273Z 
2020-07-06T11:50:13.8246401Z ======================================================================
2020-07-06T11:50:13.8246548Z FAIL: test_next_prev_minute (tests.test_xlis_calendar.XLISCalendarTestCase)
2020-07-06T11:50:13.8246866Z ----------------------------------------------------------------------
2020-07-06T11:50:13.8247005Z Traceback (most recent call last):
2020-07-06T11:50:13.8247333Z   File "/home/runner/work/trading_calendars/trading_calendars/tests/test_trading_calendar.py", line 395, in test_next_prev_minute
2020-07-06T11:50:13.8247563Z     self.calendar.previous_minute(hour_after_close)
2020-07-06T11:50:13.8247956Z AssertionError: Timestamp('1992-12-31 13:05:00+0000', tz='UTC') != Timestamp('1992-12-31 12:05:00+0000', tz='UTC')
2020-07-06T11:50:13.8248487Z     "Timestamp('1992-12-31 13:05:00+0000', tz='UTC') != Timestamp('1992-12-31 12:05:00+0000', tz='UTC')" = '%s != %s' % (safe_repr(Timestamp('1992-12-31 13:05:00+0000', tz='UTC')), safe_repr(Timestamp('1992-12-31 12:05:00+0000', tz='UTC')))
2020-07-06T11:50:13.8249139Z     "Timestamp('1992-12-31 13:05:00+0000', tz='UTC') != Timestamp('1992-12-31 12:05:00+0000', tz='UTC')" = self._formatMessage("Timestamp('1992-12-31 13:05:00+0000', tz='UTC') != Timestamp('1992-12-31 12:05:00+0000', tz='UTC')", "Timestamp('1992-12-31 13:05:00+0000', tz='UTC') != Timestamp('1992-12-31 12:05:00+0000', tz='UTC')")
2020-07-06T11:50:13.8249577Z >>  raise self.failureException("Timestamp('1992-12-31 13:05:00+0000', tz='UTC') != Timestamp('1992-12-31 12:05:00+0000', tz='UTC')")
2020-07-06T11:50:13.8249732Z     
2020-07-06T11:50:13.8249795Z 
2020-07-06T11:50:13.8249924Z ======================================================================
2020-07-06T11:50:13.8250075Z FAIL: test_next_prev_open_close (tests.test_xlis_calendar.XLISCalendarTestCase)
2020-07-06T11:50:13.8250392Z ----------------------------------------------------------------------
2020-07-06T11:50:13.8250529Z Traceback (most recent call last):
2020-07-06T11:50:13.8250747Z   File "/home/runner/work/trading_calendars/trading_calendars/tests/test_trading_calendar.py", line 357, in test_next_prev_open_close
2020-07-06T11:50:13.8250914Z     next_close, previous_close
2020-07-06T11:50:13.8251115Z   File "/home/runner/work/trading_calendars/trading_calendars/tests/test_trading_calendar.py", line 296, in _verify_minute
2020-07-06T11:50:13.8251274Z     next_close_answer
2020-07-06T11:50:13.8251655Z AssertionError: Timestamp('1992-12-31 12:05:00+0000', tz='UTC') != Timestamp('1992-12-31 13:05:00+0000', tz='UTC')
2020-07-06T11:50:13.8252189Z     "Timestamp('1992-12-31 12:05:00+0000', tz='UTC') != Timestamp('1992-12-31 13:05:00+0000', tz='UTC')" = '%s != %s' % (safe_repr(Timestamp('1992-12-31 12:05:00+0000', tz='UTC')), safe_repr(Timestamp('1992-12-31 13:05:00+0000', tz='UTC')))
2020-07-06T11:50:13.8252842Z     "Timestamp('1992-12-31 12:05:00+0000', tz='UTC') != Timestamp('1992-12-31 13:05:00+0000', tz='UTC')" = self._formatMessage("Timestamp('1992-12-31 12:05:00+0000', tz='UTC') != Timestamp('1992-12-31 13:05:00+0000', tz='UTC')", "Timestamp('1992-12-31 12:05:00+0000', tz='UTC') != Timestamp('1992-12-31 13:05:00+0000', tz='UTC')")
2020-07-06T11:50:13.8253274Z >>  raise self.failureException("Timestamp('1992-12-31 12:05:00+0000', tz='UTC') != Timestamp('1992-12-31 13:05:00+0000', tz='UTC')")
2020-07-06T11:50:13.8253424Z     
2020-07-06T11:50:13.8253486Z 
2020-07-06T11:50:13.8253617Z ======================================================================
2020-07-06T11:50:13.8253774Z FAIL: test_open_and_close_for_session (tests.test_xlis_calendar.XLISCalendarTestCase)
2020-07-06T11:50:13.8254094Z ----------------------------------------------------------------------
2020-07-06T11:50:13.8254232Z Traceback (most recent call last):
2020-07-06T11:50:13.8254454Z   File "/home/runner/work/trading_calendars/trading_calendars/tests/test_trading_calendar.py", line 780, in test_open_and_close_for_session
2020-07-06T11:50:13.8254629Z     self.assertEqual(close_answer, found_close)
2020-07-06T11:50:13.8255003Z AssertionError: Timestamp('1992-12-31 13:05:00+0000', tz='UTC') != Timestamp('1992-12-31 12:05:00+0000', tz='UTC')
2020-07-06T11:50:13.8255532Z     "Timestamp('1992-12-31 13:05:00+0000', tz='UTC') != Timestamp('1992-12-31 12:05:00+0000', tz='UTC')" = '%s != %s' % (safe_repr(Timestamp('1992-12-31 13:05:00+0000', tz='UTC')), safe_repr(Timestamp('1992-12-31 12:05:00+0000', tz='UTC')))
2020-07-06T11:50:13.8256236Z     "Timestamp('1992-12-31 13:05:00+0000', tz='UTC') != Timestamp('1992-12-31 12:05:00+0000', tz='UTC')" = self._formatMessage("Timestamp('1992-12-31 13:05:00+0000', tz='UTC') != Timestamp('1992-12-31 12:05:00+0000', tz='UTC')", "Timestamp('1992-12-31 13:05:00+0000', tz='UTC') != Timestamp('1992-12-31 12:05:00+0000', tz='UTC')")
2020-07-06T11:50:13.8256915Z >>  raise self.failureException("Timestamp('1992-12-31 13:05:00+0000', tz='UTC') != Timestamp('1992-12-31 12:05:00+0000', tz='UTC')")
2020-07-06T11:50:13.8257066Z     
2020-07-06T11:50:13.8257128Z 
2020-07-06T11:50:13.8257256Z ======================================================================
2020-07-06T11:50:13.8257408Z FAIL: test_session_closes_in_range (tests.test_xlis_calendar.XLISCalendarTestCase)
2020-07-06T11:50:13.8257728Z ----------------------------------------------------------------------
2020-07-06T11:50:13.8257870Z Traceback (most recent call last):
2020-07-06T11:50:13.8258095Z   File "/home/runner/work/trading_calendars/trading_calendars/tests/test_trading_calendar.py", line 799, in test_session_closes_in_range
2020-07-06T11:50:13.8258428Z     found_closes, self.answers['market_close']
2020-07-06T11:50:13.8258879Z   File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/pandas/util/testing.py", line 1049, in assert_series_equal
2020-07-06T11:50:13.8259202Z     check_less_precise, obj='{0}'.format(obj))
2020-07-06T11:50:13.8259440Z   File "pandas/src/testing.pyx", line 58, in pandas._testing.assert_almost_equal (pandas/src/testing.c:3887)
2020-07-06T11:50:13.8259697Z   File "pandas/src/testing.pyx", line 147, in pandas._testing.assert_almost_equal (pandas/src/testing.c:2769)
2020-07-06T11:50:13.8260164Z   File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/pandas/util/testing.py", line 915, in raise_assert_detail
2020-07-06T11:50:13.8260346Z     raise AssertionError(msg)
2020-07-06T11:50:13.8260479Z AssertionError: Series are different
2020-07-06T11:50:13.8260547Z 
2020-07-06T11:50:13.8260671Z Series values are different (0.02663 %)
```

**Comment by jenskeiner** [comment]
Thanks @gerrymanoim. Not sure what‘s behind the failure to download the logs. I just see an error when I try to expand the corresponding section. Anyway, I‘m able to run the tests locally now, so will see if I can fix and update the PR.

**Comment by gerrymanoim** [comment]
You should also be able to get the logs in the menu on the side:

image

**Comment by jenskeiner** [comment]
I think I've fixed the unit tests after adjusting the early close time to 13:05 (in WET). Please review.

The early close times (basically only New Year's Eve) before 2002, i.e. from before the acquisition by Euronext, are likely incorrect, but may have been incorrect before. I don't have any historical records or other sources to confirm.

Things to consider:
- The predecessor of the current XLIS exchange which is part of Euronext was BVLP and was formed from two exchanges, one in Porto and one in Lisbon, in the 1990s. This means they may not have observed the same early close times that this package would currently list for XLIS: see (in Portugese) https://web.archive.org/web/20110723192615/http://www.millenniumbcp.pt/site/conteudos/40/article.jhtml?articleID=375367.
- Mainland Portugal had changed the time zone from WET to CET between 1992 and 1996. Therefore, the early close times on New Year's Eve for the years 1992 to 1995 probably need to be adjusted if they are meant to be interpreted relative to the local time zone. The package currently doesn't consider this.

Might be a cleaner solution to cut off support for the old millennium. Personally, I'm only interested in most recent years and onward.

**Comment by gerrymanoim** [comment]
@jenskeiner - this makes sense to me, understood on the caveats. Thanks for the PR!

**Pull request merged**
