### PR TITLE
ENH: Fix xses

### PR DESCRIPTION
**Pull request by leonarduschen**
Trading days fix:

- Add 2018-02-19
- Remove 2019-12-15
- Add 2020-07-10
- Add 2020-11-14

Source:
https://www.tradinghours.com/exchanges/sgx/market-holidays/2018
https://www.tradinghours.com/exchanges/sgx/market-holidays/2019
https://www.tradinghours.com/exchanges/sgx/market-holidays/2020

Also changed closing time to the correct closing time from 15:00 to 17:00. This is consistent with the class' own documentation, as well as with this:

https://www.tradinghours.com/exchanges/sgx/trading-hours

### CODE REVIEW

**Comment by leonarduschen** [comment]
Note: the reason the build fails is that the test CSV is not updated after the changes.

Let me know if you want me to do that as well :)

**Comment by gerrymanoim** [comment]
Thanks for the contribution! 

According to the exchange website (https://www.sgx.com/securities/trading) they follow the government calendar at https://www.mom.gov.sg/employment-practices/public-holidays. 

Add 2018-02-19 - I can't find mention of this on the government website. See https://www.mom.gov.sg/newsroom/press-releases/2017/0405-singapore-public-holidays-2018. As best as I can tell, stocks had volume that day. 
Remove 2019-12-15 - Agreed, not listed, though this is a Sunday and shouldn't matter. 
Add 2020-07-10 - Agreed - Polling day via https://www.mom.gov.sg/employment-practices/public-holidays
Add 2020-11-14 - this is a Saturday and I don't believe it needs to be added. 

So I think only 2020-07-10 needs to be added. 

Agreed on your closing time update as well (via https://www.sgx.com/securities/trading)

**Comment by leonarduschen** [comment]
Agreed on and made your suggested changes.

Should I make changes to the CSV files as well or is it something the maintainers do?

**Comment by gerrymanoim** [comment]
Yep - if you can update the csv file as well I'll approve this and get it merged/released. Thanks!

**Pull request merged**
