### PR TITLE
Add George H.W. Bush Day of Mourning.

### PR DESCRIPTION
**Pull request by ehebert**

### CODE REVIEW

**Comment by jbredeche** [comment]
Looks like `USNationalDaysofMourning` is also used in `CMES`, `IEPA`, `XCBF` calendars.  Do we know if that is correct to add the new national day of mourning for those calendars?

**Comment by ehebert** [comment]
CMES - Will close. https://www.cmegroup.com/media-room/press-releases/2018/12/02/cme_group_u_s_equityinterestratemarketstoclosefornationaldayofmo.html

IEPA - I don't see anything on https://www.theice.com/index about closing.

XCBF - Will close. http://www.mondovisione.com/media-and-resources/news/cboe-global-markets-exchanges-to-close-wednesday-for-day-of-mourning-to-honor-p/

**Comment by jbredeche** [comment]
Good enough for me, LGTM.  better to keep all US markets consistent for now.

**Comment by chrismyles4** [comment]
re: https://github.com/quantopian/qexec/issues/16846

**Pull request merged**
