### PR TITLE
Added missing direct dependencies to install_requires

### PR DESCRIPTION
**Pull request by richafrank**
Found in https://github.com/conda-forge/trading-calendars-feedstock/pull/1

### CODE REVIEW

**Comment by gerrymanoim** [comment]
I actually don't think we should have `-e` as part of the requirements.

**Comment by gerrymanoim** [comment]
I'd lean to either (c) or (a) - apologies, should have mentioned that in my original comment.

**Comment by richafrank** [comment]
Ok, let's go with (a) the simplest choice. If it ever becomes an actual burden to update both locations, we can rethink it.

**Review by gerrymanoim — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
