### PR TITLE
TST: Add py3.9 to test matrix

### PR DESCRIPTION
**Pull request by gerrymanoim**
Drop 3.7.

### CODE REVIEW

**Comment by gerrymanoim** [comment]
Ack - looks like osx 3.9 numpy wheels still aren't quite available.

**Comment by gerrymanoim** [comment]
@richafrank So this passes CI now, but we do have a mild performance regression! Cool to see that CI in action.

**Comment by richafrank** [comment]
> So this passes CI now, but we do have a mild performance regression! Cool to see that CI in action.

So nice that we can see that! Anything obvious we should change in our numpy usage, or shall we just accept the regression?

**Comment by richafrank** [comment]
(The diff itself looks reasonable to me.)

**Comment by gerrymanoim** [comment]
There was nothing obvious in the release notes: https://github.com/numpy/numpy/releases/tag/v1.19.3. 

I was going to do some mild profiling locally, but merge this otherwise if there was nothing obvious.

**Comment by richafrank** [comment]
Sounds good to me.

**Comment by gerrymanoim** [comment]
Profiling calendar init, the difference in time is in `_all_days = date_range(start, end, freq=self.day, tz=UTC)` during the building of the calendar. 

Going to merge this as that's all outside our code and I still is a reasonable thing to do.

**Pull request merged**
