### PR TITLE
ENH: Update XLON calendars

### PR DESCRIPTION
**Pull request by gerrymanoim**
Updates XLON to include holidays from `pandas_market_calendars`. 

Closes https://github.com/quantopian/trading_calendars/issues/163.

See details from original PR: https://github.com/rsheftel/pandas_market_calendars/issues/84

### CODE REVIEW

**Comment by jmccorriston** [comment]
This looks right to me. However, the only material changes (I believe) are to the May Bank holiday going forward (2021 and later) and the May Bank holiday in 1995. Everything else looks to be just style changes, right?

**Comment by rsheftel** [comment]
Running the test suite gives this result:

```
======================================================================
ERROR: test suite for <class 'tests.test_xlon_calendar.XLONCalendarTestCase'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/tc/lib/python3.8/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/local/anaconda3/envs/tc/lib/python3.8/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/local/anaconda3/envs/tc/lib/python3.8/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/local/anaconda3/envs/tc/lib/python3.8/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/ryan/git/trading_calendars/tests/test_trading_calendar.py", line 237, in setupClass
    cls.calendar = cls.calendar_class(cls.start_date, cls.end_date)
  File "/home/ryan/git/trading_calendars/trading_calendars/trading_calendar.py", line 131, in __init__
    _overwrite_special_dates(_all_days, self._closes, _special_closes)
  File "/home/ryan/git/trading_calendars/trading_calendars/trading_calendar.py", line 1045, in _overwrite_special_dates
    raise ValueError("Special dates %s are not trading days." % bad_dates)
ValueError: Special dates [Timestamp('1999-12-31 12:30:00+0000', tz='UTC')] are not trading days.

----------------------------------------------------------------------
Ran 0 tests in 1.751s

```

**Comment by gerrymanoim** [comment]
Yep - I see the same two issue in the CI. Will sort it out.

**Comment by gerrymanoim** [comment]
Also yes - most of the changes were style, but I liked the styling in pandas market calendars better than what we previously had.

**Comment by gerrymanoim** [comment]
Right - the issue here is we have `pd.Timestamp("1999-12-31", tz='UTC')` as an adhoc holiday, but also have add special closes on `NewYearsEve` (normally it is a half day). I'm trying to figure out if LSE was actually open that day or not.

**Comment by rsheftel** [comment]
This now works for the special holidays that started this PR, but it does appear that many of the old tests fail now

**Comment by gerrymanoim** [comment]
Yep - forgot to fix the CSV. Doing that now.

**Review by rsheftel — APPROVED** [review]

**Pull request merged**
