### PR TITLE
Add calendar for Tel Aviv Stock Exchange (TASE)

### PR DESCRIPTION
**Pull request by jenskeiner**
This PR is to add a calendar for Tel Aviv Stock Exchange (TASE) under the operating MIC XTAE.

This is based on the respective calendar from `pandas-market-calendars`, but adding in holidays for 2022 and 2023 as well. I've reconciled the dates for 2019 to 2023 against the official list; see https://info.tase.co.il/eng/about_tase/corporate/pages/vacation_schedule.aspx.

Open points:
- Unclear which times to use as opening and close times as they differ per market segment; see https://info.tase.co.il/eng/trading/trading_schedule/pages/trading_schedule.aspx. Please advise.
- Different close time on Sundays not yet reflected.
- Since I don't see how holiday rules could be handled with dates in the Hebrew calendar, all holidays are defined as ad-hoc holidays. Is there a way to assign them a name, too, like for regular holidays?
- Unit tests currently only cover 2019, more should be added.

### CODE REVIEW

**Comment by jenskeiner** [comment]
Let me know any required improvements, happy to add e.g. more tests.

**Comment by gerrymanoim** [comment]
This LGTM - thanks for adding this! 

- I'd default to the open/close of the most active category (shares group A)?
- Fine to leave those as WIP
- Something could probably be build using https://pypi.org/project/pyluach/. As for naming, most of the calendars with adhoc days use comments like you did (https://github.com/quantopian/trading_calendars/blob/master/trading_calendars/exchange_calendar_xhkg.py#L171 for example). You could create `Holiday`s for each entry, but that seems overly tedious. 

@richafrank for approval/merging.

**Comment by jenskeiner** [comment]
Adjusted open/close times slightly, rest unchanged.

The continuous trading start time is random between 9:59 and 10:00 local time. The end is random between 17:14 and 17:15 local time. I've put 10:00 as open time and 17:15 as close time now since they align nicely with quarters of an hour. In any case, this ignores the randomization of the actual times.

**Comment by jenskeiner** [comment]
@gerrymanoim: I'm aware of `pyluach`. I wasn't sure how to define appropriate rules to feed to the holiday calendar. Maybe something that could be looked into in the future.

**Comment by jenskeiner** [comment]
The last commit has broken the performance check, but it looks like it wasn't actually due to any of my code changes. Possible to re-run the tests to get the checks green?

**Comment by jenskeiner** [comment]
Re-ran the tests by pushing a trivial change. All checks have passed now.

@gerrymanoim @richafrank Can someone review?

**Comment by gerrymanoim** [comment]
Sorry - I no longer have review/approve/merge access (that seems to have gotten lost in the shuffle). I think @richafrank or @jbredeche are the only ones?

**Review by gerrymanoim — APPROVED** [review]

**Pull request merged**
