### PR TITLE
ENH: Update XHKG calendar

### PR DESCRIPTION
**Pull request by gerrymanoim**
WIP PR for updating XHKG. See details here: https://github.com/quantopian/trading_calendars/issues/152#issuecomment-689799967.

Pausing for now as:

- I need to do a bit more refactoring to get Buddha's birthday/other lunar holidays ported over correctly from `pandas_market_calendars`
- I need clarification from @jmccorriston on `Liberation Day` (I can't see that in either calendar?)
- I need some other clarification about whether we're pulling the rest of the missing holidays from PMC (which I believe to be the case, but I wanted to double check).

### CODE REVIEW

**Comment by jmccorriston** [comment]
Liberation Day is another name for Allied Victory Day https://en.wikipedia.org/wiki/Victory_over_Japan_Day, which is currently implemented here in pmc: https://github.com/rsheftel/pandas_market_calendars/blob/master/pandas_market_calendars/exchange_calendar_hkex.py#L240.

In general, I think we should port over the rest of the holidays from pmc.

**Comment by gerrymanoim** [comment]
@jmccorriston - updated, I think I grabbed them all, will run another check when I have a sec.

**Comment by gerrymanoim** [comment]
Confirmed no more diffs between the two calendars.

**Comment by jmccorriston** [comment]
Sorry for the delay, this lgtm then!

**Review by jmccorriston — APPROVED** [review]

**Pull request merged**
